// <auto-generated />
using System;
using EventTracker.config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventTracker.models.EventBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("event_type");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("integer")
                        .HasColumnName("max_participants");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_events_created_by_user_id");

                    b.ToTable("events", (string)null);

                    b.HasDiscriminator<string>("EventType").HasValue("EventBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EventTracker.models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_participants");

                    b.ToTable("participants", (string)null);
                });

            modelBuilder.Entity("EventTracker.models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime?>("CheckedInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_in_at");

                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer")
                        .HasColumnName("participant_id");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int?>("WaitingPosition")
                        .HasColumnType("integer")
                        .HasColumnName("waiting_position");

                    b.HasKey("Id")
                        .HasName("pk_registrations");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_registrations_event_id");

                    b.HasIndex("ParticipantId")
                        .HasDatabaseName("ix_registrations_participant_id");

                    b.ToTable("registrations", (string)null);
                });

            modelBuilder.Entity("EventTracker.models.ScheduleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasJsonPropertyName("createdAt");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasJsonPropertyName("description");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at")
                        .HasJsonPropertyName("endAt");

                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("event_id")
                        .HasJsonPropertyName("eventId");

                    b.Property<string>("Room")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("room")
                        .HasJsonPropertyName("room");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at")
                        .HasJsonPropertyName("startAt");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title")
                        .HasJsonPropertyName("title");

                    b.HasKey("Id")
                        .HasName("pk_schedule_items");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_schedule_items_event_id");

                    b.ToTable("schedule_items", (string)null);
                });

            modelBuilder.Entity("EventTracker.models.ScheduleItemSpeaker", b =>
                {
                    b.Property<int>("ScheduleItemId")
                        .HasColumnType("integer")
                        .HasColumnName("schedule_item_id");

                    b.Property<int>("SpeakerId")
                        .HasColumnType("integer")
                        .HasColumnName("speaker_id");

                    b.HasKey("ScheduleItemId", "SpeakerId")
                        .HasName("pk_schedule_item_speakers");

                    b.HasIndex("SpeakerId")
                        .HasDatabaseName("ix_schedule_item_speakers_speaker_id");

                    b.ToTable("schedule_item_speakers", (string)null);
                });

            modelBuilder.Entity("EventTracker.models.Speaker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.HasKey("Id")
                        .HasName("pk_speakers");

                    b.ToTable("speakers", (string)null);
                });

            modelBuilder.Entity("EventTracker.models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EventTracker.models.Conference", b =>
                {
                    b.HasBaseType("EventTracker.models.EventBase");

                    b.Property<bool>("HasExhibition")
                        .HasColumnType("boolean")
                        .HasColumnName("has_exhibition");

                    b.Property<decimal?>("RegistrationFee")
                        .HasColumnType("numeric")
                        .HasColumnName("registration_fee");

                    b.Property<int?>("TrackCount")
                        .HasColumnType("integer")
                        .HasColumnName("track_count");

                    b.HasDiscriminator().HasValue("Conference");
                });

            modelBuilder.Entity("EventTracker.models.Seminar", b =>
                {
                    b.HasBaseType("EventTracker.models.EventBase");

                    b.Property<bool>("IsInteractive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_interactive");

                    b.Property<int?>("MaxAttendees")
                        .HasColumnType("integer")
                        .HasColumnName("max_attendees");

                    b.Property<string>("Topic")
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.HasDiscriminator().HasValue("Seminar");
                });

            modelBuilder.Entity("EventTracker.models.Workshop", b =>
                {
                    b.HasBaseType("EventTracker.models.EventBase");

                    b.Property<string>("MaterialsRequired")
                        .HasColumnType("text")
                        .HasColumnName("materials_required");

                    b.Property<int?>("SkillLevel")
                        .HasColumnType("integer")
                        .HasColumnName("skill_level");

                    b.Property<decimal>("WorkshopFee")
                        .HasColumnType("numeric")
                        .HasColumnName("workshop_fee");

                    b.HasDiscriminator().HasValue("Workshop");
                });

            modelBuilder.Entity("EventTracker.models.EventBase", b =>
                {
                    b.HasOne("EventTracker.models.User", "CreatedByUser")
                        .WithMany("CreatedEvents")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_events_users_created_by_user_id");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("EventTracker.models.Registration", b =>
                {
                    b.HasOne("EventTracker.models.EventBase", "Event")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_registrations_events_event_id");

                    b.HasOne("EventTracker.models.Participant", "Participant")
                        .WithMany("Registrations")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_registrations_participants_participant_id");

                    b.Navigation("Event");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("EventTracker.models.ScheduleItem", b =>
                {
                    b.HasOne("EventTracker.models.EventBase", "Event")
                        .WithMany("ScheduleItems")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_items_events_event_id");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventTracker.models.ScheduleItemSpeaker", b =>
                {
                    b.HasOne("EventTracker.models.ScheduleItem", "ScheduleItem")
                        .WithMany("ScheduleItemSpeakers")
                        .HasForeignKey("ScheduleItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_item_speakers_schedule_items_schedule_item_id");

                    b.HasOne("EventTracker.models.Speaker", "Speaker")
                        .WithMany("ScheduleItemSpeakers")
                        .HasForeignKey("SpeakerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_item_speakers_speakers_speaker_id");

                    b.Navigation("ScheduleItem");

                    b.Navigation("Speaker");
                });

            modelBuilder.Entity("EventTracker.models.EventBase", b =>
                {
                    b.Navigation("Registrations");

                    b.Navigation("ScheduleItems");
                });

            modelBuilder.Entity("EventTracker.models.Participant", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("EventTracker.models.ScheduleItem", b =>
                {
                    b.Navigation("ScheduleItemSpeakers");
                });

            modelBuilder.Entity("EventTracker.models.Speaker", b =>
                {
                    b.Navigation("ScheduleItemSpeakers");
                });

            modelBuilder.Entity("EventTracker.models.User", b =>
                {
                    b.Navigation("CreatedEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
