START TRANSACTION;
ALTER TABLE events ADD created_by_user_id integer NOT NULL DEFAULT 0;

CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    email character varying(200) NOT NULL,
    password_hash text NOT NULL,
    phone character varying(50),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE INDEX ix_events_created_by_user_id ON events (created_by_user_id);

ALTER TABLE events ADD CONSTRAINT fk_events_users_created_by_user_id FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260130174811_AddUserAndAuth', '10.0.1');

COMMIT;

